### ISSUE TITLE
Could not resolve `@vueuse/shared` on `2.0.0-beta.9`

### ISSUE THREAD

**Issue by salazarr-js** [vueuse/motion#47]
Trying to replicate the [pinch example](https://github.com/vueuse/gesture/blob/main/docs/.vitepress/components/demos/PinchExample.vue) from `@vueuse/gesture` I found that after installing the lib with `npm i @vueuse/motion`, `vite` started to fail showing a `Could not resolve "@vueuse/shared"` error message

#### `npm run dev`
```sh
> vite
> node_modules/@vueuse/motion/dist/index.mjs:3:43: error: Could not resolve "@vueuse/shared" (mark it as external to exclude it from the bundle)
    3 │ import { tryOnUnmounted, isFunction } from '@vueuse/shared';
      ╵                                            ~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/@vueuse/motion/dist/index.mjs:3:43: error: Could not resolve "@vueuse/shared" (mark it as external to exclude it from the bundle)
    at failureErrorWithLog (/.../node_modules/esbuild/lib/main.js:1493:15)
    at /.../node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/.../node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/.../node_modules/esbuild/lib/main.js:1149:7)
    at /.../node_modules/esbuild/lib/main.js:1258:14
    at /.../node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/.../node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/.../node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

#### `npm run build`

```sh
> vue-tsc --noEmit && vite build

node_modules/@vueuse/motion/dist/index.d.ts:7:40 - error TS2307: Cannot find module '@vueuse/shared' or its corresponding type declarations.

7 import { MaybeRef as MaybeRef$1 } from '@vueuse/shared';
```

#### `package.json`
```json
{
  "dependencies": {
    "@vueuse/core": "^7.5.4",
    "@vueuse/gesture": "^2.0.0-beta.1",
    "@vueuse/motion": "^2.0.0-beta.9",
    "vue": "^3.2.25"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.0.0",
    "typescript": "^4.4.4",
    "vite": "^2.7.2",
    "vue-tsc": "^0.29.8"
  }
}
```

#### Just trying to import the composable make the serve/build fails
```ts
import { useMotion } from '@vueuse/motion'
```

#### System info 
**node`v16.13.1`**
**npm `v8.1.2`**
**macOs Big Sur `v11.2.3`**
**Chrome `v97.0.4692.71`**

**Comment by Of3lia** [comment]
Im having the same problem when I try go use MotionPlugin, Im using Typescript Vue 3 Vite

**Comment by hopkins385** [comment]
Same here, using Vite + Vue 3 + Typescript. `npm i @vueuse/shared` solved the issue for dev-build but keeps throwing issues for the production-build. 

`node_modules/@vueuse/motion/dist/index.d.ts:137:31 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

137         colorAdjust?: csstype.ColorAdjustProperty | undefined;
                                  ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:637:42 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'. 

637         WebkitPrintColorAdjust?: csstype.ColorAdjustProperty | undefined;
                                             ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:911:34 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'. 

911         "color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                     ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:1373:48 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

1373         "-webkit-print-color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                                    ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:1691:31 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

1691         colorAdjust?: csstype.ColorAdjustProperty | undefined;
                                   ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:2191:42 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

2191         WebkitPrintColorAdjust?: csstype.ColorAdjustProperty | undefined;
                                              ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:2465:34 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

2465         "color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                      ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:2927:48 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

2927         "-webkit-print-color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                                    ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:3264:31 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

3264         colorAdjust?: csstype.ColorAdjustProperty | undefined;
                                   ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:3764:42 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

3764         WebkitPrintColorAdjust?: csstype.ColorAdjustProperty | undefined;
                                              ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:4038:34 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

4038         "color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                      ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:4500:48 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

4500         "-webkit-print-color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                                    ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:4777:35 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

4777             colorAdjust?: csstype.ColorAdjustProperty | undefined;
                                       ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:5285:46 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

5285             WebkitPrintColorAdjust?: csstype.ColorAdjustProperty | undefined;
                                                  ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:5559:38 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

5559             "color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                          ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:6021:52 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

6021             "-webkit-print-color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                                        ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:6704:31 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

6704         colorAdjust?: csstype.ColorAdjustProperty | undefined;
                                   ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:7204:42 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

7204         WebkitPrintColorAdjust?: csstype.ColorAdjustProperty | undefined;
                                              ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:7478:34 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

7478         "color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                      ~~~~~~~~~~~~~~~~~~~

node_modules/@vueuse/motion/dist/index.d.ts:7940:48 - error TS2694: Namespace '"E:/htdocs_play/vite-faiwr-v1/node_modules/csstype/index"' has no exported member 'ColorAdjustProperty'.

7940         "-webkit-print-color-adjust"?: csstype.ColorAdjustProperty | undefined;
                                                    ~~~~~~~~~~~~~~~~~~~


Found 20 errors in the same file, starting at: node_modules/@vueuse/motion/dist/index.d.ts:137`

**Comment by Tahul** [comment]
Hello :)

I couldn't reproduce the problem on my end, but found some spots that could be faulty in the package config!

I pushed some changes that should solve both of your errors, @salazarr-js and @hopkins385.

I tried the package there:
https://github.com/Tahul/vueuse-motion-test

As I have a working reproduction, I am closing this issue, but feel free to reopen and tell me if anything breaks for you!

Thanks a lot for your issue and comments! 🙏
