### ISSUE TITLE
Cant use vueuse/motion library, this error comes up

### ISSUE THREAD

**Issue by kiranraaj19** [vueuse/motion#66]
Package subpath './nuxt' is not defined by "exports" in /home/kiranraajsekar/coding/kslife/node_modules/@vueuse/motion/package.json

  at new NodeError (node:internal/errors:372:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:753:3)
  at resolveExports (node:internal/modules/cjs/loader:482:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:192841)
  at Resolver.jiti [as _require] (node_modules/jiti/dist/jiti.js:1:195025)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)

││   ✖ Nuxt Fatal Error││  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './nuxt'  is not defined by "exports" in                                             ││   /home/kiranraajsekar/coding/kslife/node_modules/@vueuse/motion/package.json

**Comment by kiranraaj19** [comment]
Solved by changing version from ^2.0.0-beta.12 to ^2.0.0-beta.18
