### ISSUE TITLE
Issue while building with ViteSSG

### ISSUE THREAD

**Issue by ArgekarStudios** [vueuse/motion#79]
TypeError: Cannot read properties of null (reading 'props')
    at Object.getSSRProps (file:///home/king/projects/digiResumeWeb/node_modules/.pnpm/@vueuse+motion@2.0.0-beta.12_vue@3.2.37/node_modules/@vueuse/motion/dist/index.mjs:1101:47)
    at ssrGetDirectiveProps (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:707:21)
    at file:///home/king/projects/digiResumeWeb/.vite-ssg-temp/main.mjs:2842:156
    at renderComponentSubTree (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:250:13)
    at renderComponentVNode (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
    at ssrRenderComponent (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender (file:///home/king/projects/digiResumeWeb/.vite-ssg-temp/main.mjs:2902:9)
    at renderComponentSubTree (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:250:13)
    at renderComponentVNode (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
    at renderVNode (/home/king/projects/digiResumeWeb/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:292:22)
    at file:///home/king/projects/digiResumeWeb/node_modules/.pnpm/vite-ssg@0.20.2_nro6d7s7gsixoieiq2nt5jvtfq/node_modules/vite-ssg/dist/chunks/build.mjs:218:15
    at async run (/home/king/projects/digiResumeWeb/node_modules/.pnpm/p-queue@6.6.2/node_modules/p-queue/dist/index.js:163:29)

**Comment by rashidpathiyil** [comment]
Same issue, any fix?

**Comment by rashidpathiyil** [comment]
Ref #73

**Comment by Tahul** [comment]
@rashidpathiyil ; could you please try: `^2.0.0-beta.22` please?

Also, a reproduction would be amazing 🙏

As a way to prevent future breakings, I added a playground using `vite-ssg` in the repository, and will be running a build with it on each commit CI now. :)

**Comment by Tahul** [comment]
I am closing this in favor of #73
